name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_BEACH_0C8401E1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"

          # Configuração para projeto Angular na raiz do repositório:
          # - app_location aponta para a pasta que contém package.json/angular.json
          # - app_build_command compila o app
          # - output_location aponta para a pasta final do build que contém index.html
          app_location: "."                             # projeto na raiz do repositório
          app_build_command: "npm ci && npm run build"  # comando de build do Angular
          output_location: "dist/tarefas-ng/browser"    # saída do Angular 15+ com pasta browser

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_BEACH_0C8401E1E }}
          action: "close"
